#! /usr/bin/python

from blessings import Terminal
from time import time
from os import system
from sys import argv

if len(argv) == 2:
    MAIN_CODE_BASE_NAME = argv[1]
else:
    MAIN_CODE_BASE_NAME = "app"

MAIN_CODE_EXTENSION = "cpp"
MAIN_CODE_FILE = MAIN_CODE_BASE_NAME + '.' + MAIN_CODE_EXTENSION

# Initialise blessings module for colored output
term = Terminal()

# Function to execute command locally
def exec(cmd):
    res = system(cmd)
    return res == 0

# Compile main code file
def main():
    st = time()

    # Uncomment this if you want debug flags
    # executed = exec(f"g++ -std=c++17 -O2 -Wshadow -Wextra -Wall -fsanitize=address -fsanitize=undefined -D_GLIBCXX_DEBUG {MAIN_CODE_FILE} -o {MAIN_CODE_BASE_NAME}")

    # Normal compile flags
    executed = exec(f"g++ -std=c++17 -O2 {MAIN_CODE_FILE} -o {MAIN_CODE_BASE_NAME}")

    et = time()

    if not executed:
        print(term.bold(term.red(f"[FAIL] {MAIN_CODE_FILE} Compilation failed")))
        exit(1)

    print(term.bold(term.green(f"[OK] {MAIN_CODE_FILE} Compiled successfully")))
    delta = str(round(et-st, 3)) + 's'
    print(term.blue("Compile Time: "), term.bold(term.green((delta))))

    return 0

if __name__ == '__main__':
    main()
