#!/bin/sh

# Pull dbg-macro
git clone https://github.com/sharkdp/dbg-macro.git --depth 1
cp dbg-macro/dbg.h dbg.hpp

# Copy template into app.cpp
cp Snippets/template.cpp .
cp template.cpp app.cpp

# Remove unnecessary directories
rm -rf .git .gitignore README.md Snippets Scripts dbg-macro

# Create input file
touch in

