#! /usr/bin/bash

# Remove .git, .gitignore, and README.md
rm -rf .git .gitignore README.md

files=(
    "Snippets/tl.hpp"
    "Scripts/Makefile"
)

# Copy each file in files to the current directory
for file in "${files[@]}"; do
    cp -r "$file" .
done

# Remove snippets and scripts directory
rm -rf Snippets Scripts

# Precompile tl.hpp
g++ -std=c++17 -O2 -DLOCAL tl.hpp

# Create app.cpp and in
touch app.cpp
touch in