#! /usr/bin/bash

# Remove .git, .gitignore, and README.md
rm -rf .git .gitignore README.md

files=(
    "Scripts/Makefile"
)

# Copy each file in files to the current directory
for file in "${files[@]}"; do
    cp -r "$file" .
done

# Remove snippets and scripts directory
rm -rf Snippets Scripts

# Clone dbg-macro
git clone https://github.com/sharkdp/dbg-macro.git --depth 1

# Copy dbg.h to current directory
cp dbg-macro/dbg.h .

# Remove dbg-macro repository
rm -rf dbg-macro

# Create app.cpp and in
touch app.cpp
touch in