#!/usr/bin/python3

from os import system

MAIN_CODE_EXECUTABLE = "app"
BRUTE_CODE_EXECUTABLE = "brute"
GEN_CODE_EXECUTABLE = "gen"


def fileExists(fileName):
    try:
        open(fileName, "r")
        return True
    except FileNotFoundError:
        return False


def main():
    assert fileExists(MAIN_CODE_EXECUTABLE), f"./{MAIN_CODE_EXECUTABLE} not found"
    assert fileExists(BRUTE_CODE_EXECUTABLE), f"./{BRUTE_CODE_EXECUTABLE} not found"
    assert fileExists(GEN_CODE_EXECUTABLE), f"./{GEN_CODE_EXECUTABLE} not found"

    tests = int(input("Enter number of tests: "))
    for t in range(1, tests + 1):
        system(f"./{GEN_CODE_EXECUTABLE} > in")
        system(f"./{MAIN_CODE_EXECUTABLE} < in > out")
        system(f"./{BRUTE_CODE_EXECUTABLE} < in > brute_out")
        if system("wdiff out brute_out > /dev/null") != 0:
            print(f"[WA] Test {t} failed")
            print("Failed test case:")
            system(f"cat in")
            exit(1)
        else:
            print(f"[AC] Test {t} passed")

    system(f"rm in out brute_out")


if __name__ == "__main__":
    main()
